## File: examples/amplitude-control.yaml

# AD9833 with MCP41010 Amplitude Control Example
# Adds digital potentiometer for amplitude adjustment

substitutions:
  device_name: ad9833-amplitude
  friendly_name: "AD9833 Amplitude Control"

esphome:
  name: ${device_name}

esp32:
#  board: heltec_wifi_kit_32
  board: esp32dev
#  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

# External component
external_components:
  - source: github://roblamoreaux/esphome-ad9833
    components: [ ad9833 ]

# SPI Bus
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

# AD9833 with MCP41010
ad9833:
  id: sig_gen
  cs_pin: GPIO5
  digipot_cs_pin: GPIO15  # MCP41010 CS pin
  frequency: 1000.0
  waveform: SINE
  amplitude: 50.0

# Controls
number:
  - platform: template
    name: "Frequency"
    min_value: 10
    max_value: 20000
    step: 1
    initial_value: 1000
    unit_of_measurement: "Hz"
    optimistic: true
    set_action:
      - lambda: id(sig_gen)->set_frequency(x);

  - platform: template
    name: "Amplitude"
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 50
    unit_of_measurement: "%"
    optimistic: true
    set_action:
      - lambda: id(sig_gen)->set_amplitude(x);

select:
  - platform: template
    name: "Waveform"
    options:
      - "Sine"
      - "Triangle"
      - "Square"
    initial_option: "Sine"
    optimistic: true
    set_action:
      - lambda: |-
          int waveform = 0;
          if (x == "Sine") waveform = 0;
          else if (x == "Triangle") waveform = 1;
          else if (x == "Square") waveform = 2;
          id(sig_gen)->set_waveform((ad9833::WaveformType)waveform);

# Quick amplitude presets
button:
  - platform: template
    name: "Low Signal (10%)"
    on_press:
      - lambda: id(sig_gen)->set_amplitude(10);

  - platform: template
    name: "Medium Signal (50%)"
    on_press:
      - lambda: id(sig_gen)->set_amplitude(50);

  - platform: template
    name: "High Signal (90%)"
    on_press:
      - lambda: id(sig_gen)->set_amplitude(90);

# AM Modulation example
  - platform: template
    name: "Start AM Modulation"
    on_press:
      - lambda: |-
          id(sig_gen)->set_modulation(
            ad9833::MOD_AM,
            5.0,    // 5 Hz modulation
            0.5     // 50% depth
          );

